### ISSUE TITLE
Window title has 'UUU' at the end.

### ISSUE THREAD

**Issue by ghost** [PolyplexEngine/libpp#9]
![screenshot from 2018-03-19 18-03-02](https://user-images.githubusercontent.com/28670385/37610395-63bf490a-2b97-11e8-9240-0896fc2a467d.png)
Window title has UUU at the end when it's longer than 7 characters.

**Comment by LunaTheFoxgirl** [comment]
I will look into this asap.

Can you please provide the code you are trying to run?

**Comment by ghost** [comment]
https://pastebin.com/GXpEiapP

**Comment by LunaTheFoxgirl** [comment]
Fixed in newest commit, please check.
